### ISSUE TITLE
6798.4 DEV update languages and services add patch updates

### ISSUE THREAD

**Issue by deepikasl** [dry-dock/u14all#11]
https://github.com/Shippable/pm/issues/6798

**Comment by deepikasl** [comment]
This is complete.

**Comment by ankul-shippable** [comment]
reopening this for more updates

**Comment by stephanielingwood** [comment]
In updating the u14all files for u16, we made some changes to use newer/correct versions of services. We should probably make those changes to u14all. They are:

- elasticsearch: 2.4.1 is the latest stable version
- mysql: 5.7 is the lastest stable version
- neo4j: 3.0.6 is the latest stable version
- rethinkdb: in the download url, it should be trusty (u14), not precise (u12) in the url
- riak: in the download url, it should be trusty (u14), not precise (u12) in the url
