### ISSUE TITLE
update mysql and postgres in u14all

### ISSUE THREAD

**Issue by bindushree16** [dry-dock/u14all#140]
https://github.com/Shippable/pm/issues/10588

**Comment by ric03uec** [comment]
looks good

**Comment by bindushree16** [comment]
build success

https://app.shippable.com/github/Shippable/jobs/all_x86_64_Ubuntu_14_04_prep/builds/5ac749bb07829a07002050cf/console

**Comment by bindushree16** [comment]
verified and tested

https://rcapp.shippable.com/github/bindushree16/jobs/u14all-test/builds/5ac75863b020a805000711b4/console

**Comment by ric03uec** [comment]
Looks good, closing
