### ISSUE TITLE
10816.1 Update cassandra version 

### ISSUE THREAD

**Issue by vijayreddy1991** [dry-dock/u14all#147]
https://github.com/Shippable/pm/issues/10816

## Tasks
1. Update cassandra version to 3.11
## Tests
1. Test cassandra is starting/stopping correctly when drydock/u14all:master is used as custom image in CI build
2. Test that user is able to connect to cassandra from build yml

**Comment by vijayreddy1991** [comment]
Build is success

https://app.shippable.com/github/Shippable/jobs/u14all_x8664_build/builds/5af444728d35310700bf59bd/console

**Comment by vijayreddy1991** [comment]
Tested and verified

https://rcapp.shippable.com/github/vijayreddy1991/u14cassandra-test/runs/6/1/console

**Comment by ric03uec** [comment]
@vijayreddy1991 the link above is giving 404

**Comment by vijayreddy1991** [comment]
Could you please check now its working fine

**Comment by ric03uec** [comment]
looks ok, closing
