### ISSUE TITLE
10816.2 Update couchdb version

### ISSUE THREAD

**Issue by vijayreddy1991** [dry-dock/u14all#148]
https://github.com/Shippable/pm/issues/10816

## Tasks
1. Update couchdb version to 2.1.1
## Tests
1. Test couchdb is starting/stopping correctly when drydock/u14all:master is used as custom image in CI build
2. Test that user is able to connect to couchdb from build yml

**Comment by vijayreddy1991** [comment]
Build is success 

https://app.shippable.com/github/Shippable/jobs/u14all_x8664_build/builds/5af444728d35310700bf59bd/console

**Comment by vijayreddy1991** [comment]
Verified and tested

https://rcapp.shippable.com/github/vijayreddy1991/u14couchdb-test/runs/3/1/console

**Comment by ric03uec** [comment]
tests look good, closing
