### ISSUE TITLE
10816.3 Update elastic search version

### ISSUE THREAD

**Issue by vijayreddy1991** [dry-dock/u14all#149]
https://github.com/Shippable/pm/issues/10816

## Tasks
1. Update elastic search version 6.2.3 to 6.2.4
## Tests
1. Test elastic search is starting/stopping correctly when drydock/u14all:master is used as custom image in CI build
2. Test that user is able to connect to elastic search from build yml

**Comment by vijayreddy1991** [comment]
Build is success

https://app.shippable.com/github/Shippable/jobs/u14all_x8664_build/builds/5af55159be61c907004fac0d/console

**Comment by ric03uec** [comment]
@vijayreddy1991 why is elasticsarch version command throwing nvm errors. we need to investigate this

**Comment by vijayreddy1991** [comment]
ok

**Comment by vijayreddy1991** [comment]
This is happening because of this https://github.com/dry-dock/u14/blob/89413c66eff70c74f4d8943a9f78ff780b80b71b/node/install.sh#L10. elasticsearch runs as elasticsearch user but nvm is in root, should we change drydock env to root.
