### ISSUE TITLE
10816.4 Update memcached version

### ISSUE THREAD

**Issue by vijayreddy1991** [dry-dock/u14all#151]
https://github.com/Shippable/pm/issues/10816

## Tasks
1. Update memcached version 1.5.7
## Tests
1. Test memcached is starting/stopping correctly when drydock/u14all:master is used as custom image in CI build
2. Test that user is able to connect to memcached from build yml

**Comment by vijayreddy1991** [comment]
Build is success

https://app.shippable.com/github/Shippable/jobs/u14all_x8664_build/builds/5af55159be61c907004fac0d/console

**Comment by vijayreddy1991** [comment]
Verified and tested

https://rcapp.shippable.com/github/vijayreddy1991/u14memcached-test/runs/1/1/console

**Comment by ric03uec** [comment]
looks good, closing
