### ISSUE TITLE
10816.5 Update riak version

### ISSUE THREAD

**Issue by vijayreddy1991** [dry-dock/u14all#152]
https://github.com/Shippable/pm/issues/10816

## Tasks
1. Update riak version 2.2.3
## Tests
1. Test riak is starting/stopping correctly when drydock/u14all:master is used as custom image in CI build
2. Test that user is able to connect to riak from build yml

**Comment by vijayreddy1991** [comment]
Build is success

https://app.shippable.com/github/Shippable/jobs/u14all_x8664_build/builds/5af55159be61c907004fac0d/console

**Comment by vijayreddy1991** [comment]
Verified and tested

https://rcapp.shippable.com/github/vijayreddy1991/u14riak-test/runs/1/1/console

**Comment by ric03uec** [comment]
looks good,closing
