### ISSUE TITLE
10816.7 Update neo4j version

### ISSUE THREAD

**Issue by vijayreddy1991** [dry-dock/u14all#155]
https://github.com/Shippable/pm/issues/10816

## Tasks
1. Update neo4j version 3.3.4 to 3.3.5
## Tests
1. Test neo4j is starting/stopping correctly when drydock/u14all:master is used as custom image in CI build
2. Test that user is able to connect to neo4j from build yml

**Comment by vijayreddy1991** [comment]
Build is success

https://app.shippable.com/github/Shippable/jobs/u14all_x8664_build/builds/5af58915be61c907004fc779/console

**Comment by vijayreddy1991** [comment]
Verified and tested 

https://rcapp.shippable.com/github/vijayreddy1991/u14neo4j-test/runs/1/1/console

**Comment by ric03uec** [comment]
looks good, closing
