### ISSUE TITLE
10816.8 Update rabbitmq version

### ISSUE THREAD

**Issue by vijayreddy1991** [dry-dock/u14all#156]
https://github.com/Shippable/pm/issues/10816

## Tasks
1. Update rabbitmq version 3.6.15
## Tests
1. Test rabbitmq is starting/stopping correctly when drydock/u14all:master is used as custom image in CI build
2. Test that user is able to connect to rabbitmq from build yml

**Comment by vijayreddy1991** [comment]
Build is success

https://app.shippable.com/github/Shippable/jobs/u14all_x8664_build/builds/5af56965a55fb8070036db73/console

**Comment by vijayreddy1991** [comment]
Verified and tested

https://rcapp.shippable.com/github/vijayreddy1991/u14rabbitmq-test/runs/1/1/console

**Comment by ric03uec** [comment]
looks good, closing
