### ISSUE TITLE
Dev MVP 3 Update couchdb version in u14all from 1.6.1 to 2.0.0 

### ISSUE THREAD

**Issue by rai-sushmitha** [dry-dock/u14all#37]
from https://github.com/Shippable/pm/issues/8613

**Comment by ric03uec** [comment]
@kanthchandra can this be closed?

**Comment by kanthchandra** [comment]
We couldn't update couchdb in this release. I have spoken to @rageshkrishna about this. We were running into a race condition while installing and it was taking a lot time. So we should do this in the next release v5.8.1.
